language: ruby
script: "bundle exec rake spec SPEC_OPTS='--color --format documentation'"
rvm:
  - 1.9.3
  - 2.0.0
env:
  - PUPPET_GEM_VERSION=">= 3.0.0"
matrix:
  allow_failures:
    - rvm: 2.0.0
    - rvm: ruby-head
notifications:
  email: false
gemfile: Gemfile
